version: '2'

services:
  raspbian:
    image: resin/rpi-raspbian:wheezy

  python_client:
    build:
      context: .
      dockerfile: docker/python/Dockerfile

  python_server:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
